# Generated by Django 4.2.7 on 2024-02-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('la_tache', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
            ],
        ),
    ]
