# Generated by Django 4.2.7 on 2024-02-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_daily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='lieu',
            new_name='bool',
        ),
    ]
